version: '2'
services:
    nginx:
        container_name: nginx-container
        build: nginx
        ports:
            - 80:80
        volumes:
            - ../.:/var/www/app

    php:
        container_name: php-container
        build: php
        volumes:
            - ../.:/var/www/app
        working_dir: /var/www/app
        environment:
            - SYMFONY_ENV=dev

    redis:
        container_name: redis-container
        image: redis:latest
        ports:
            - 6379:6379
